project:
  type: website

website:
  title: "Isabelle Langrock"
  navbar:
    background: "#d0f0c0" 
    foreground: "#123524"
    right:
      - href: index.qmd
        text: "Home"
      - Research.qmd
      - Teaching.qmd
      - News.qmd
  page-footer: 
    right: "Last updated: August 2022" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



