project:
  type: website
  output-dir: docs

  

website:
  title: "Isabelle Langrock, PhD"
  navbar:
    background: "#d0f0c0" 
    foreground: "#123524"
    right:
      - href: index.qmd
        text: "Home"
      - CV.qmd
      - Research.qmd
      - Teaching.qmd
      - News.qmd

  page-footer: 
    right: "Last updated: August 2024" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      body-width: 900px
      margin-width: 300px
      gutter-width: 5em




