project:
  type: website
  output-dir: docs

  

website:
  title: "Isabelle Langrock"
  navbar:
    background: "#d0f0c0" 
    foreground: "#123524"
    right:
      - href: index.qmd
        text: "Home"
      - Research.qmd
      - Teaching.qmd
      - News.qmd
  page-footer: 
    right: "Last updated: July 2023" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




