---
title: "News & Events"
---

* Back in Philly to present some preliminary findings from my project *Social Science in the Post API Age* at IC2S2 (July 2024)

* New article published in PNAS NEXUS: [Book Bans in Political Context](https://academic.oup.com/pnasnexus/article/3/6/pgae197/7689238?login=true) (June 2024)

* I met with my co-author Katie Spoon in Copenhagen to present our work on books bans at IC2S2 (July 2023) 

* I moved to Paris, France to begin a postdoc with Jen Schradie at the Center for Research on Social Inequalities at Sciences Po (June 2023)

* I successfully defend my dissertation "The Irony of Openness: Gender Inequality in Self-Governed Knowledge Systems"  (May 2023)

* My article with Sandra González-Bailón about Interventions in Wikipedia's Gender Gaps wins the [Wikimedia Foundation Research Award of The Year](https://research.wikimedia.org/awards.html) for 2023!! 

* I discussed *How Wikipedia Works* on the Brooking's Institute Tech Tank Podcast (March 2023)
  + Listen [here](https://www.brookings.edu/articles/techtank-episode-66-how-wikipedia-works/)

* *I led an Art + Feminism Community Hour Session* (September 2022)
  + Details [here](https://artandfeminism.org/research-closing-wikipedias-gender-gaps/)

* A nice article summarizing my work: [*Bridging Wikipedia’s Gender Gap, One Article at a Time*](https://www.asc.upenn.edu/news-events/news/bridging-wikipedias-gender-gap-one-article-time) (Penn News, 2022) by Alina Ladyzhensky

* I presented at the *WikiMedia Research Showcase* (July 2021) 
  + <iframe width="560" height="315" src="https://www.youtube.com/embed/otN3H-hIImQ?start=2151" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>