---
title: "Teaching"
---

Drawing from my own research on digital inequalities, I believe that students need a comprehensive education in the many ways that technology shapes and informs their lives. Whether I am teaching research methods, coding skills, or theory based seminars, my syllabus features real-world connections where students apply the material to events and content relevant to their lives. 

I'm happy to give guest lectures at the undergraduate or graduate level introducing computational methods or discussing my research on information environments.  

# Teaching Materials 
::: {.grid}
::: {.g-col-6}
## <span style="color:#9ec995;">Digital Feminisms Syllabus </span>
The [syllabus](https://drive.google.com/file/d/1WXeTu9a-mgA2G--py5M60LUe1DUK6GDZ/view?usp=sharing) for my undergraduate seminar in the Sociology department at Sciences Po in Spring 2024. (English)


## <span style="color:#9ec995;">Wikipedia Editing Assignment </span>
Original assignment for an undergraduate seminar course. Students edit Wikipedia using on course concepts and are prompted to reflect about digital collaborations and inequities. 

:::

::: {.g-col-6}
## <span style="color:#9ec995;"> R Labs </span>
Lab assignments for Comm 522: Intro to Research Methods (required class for first year grad assignments). Designed to introduce students to R and the basics of quantitative social science research. 
[Github repository here.](https://github.com/islangrock/Comm522_Labs)


## <span style="color:#9ec995;">Github Training</span>
*Using Github for Social Science Research Tutorial* 
designed for the DiMeNet Research Group (Fall 2021).
[Find presentation here.](https://github.com/islangrock/Github_Practice/blob/main/2021_10presentation.pdf)

:::
:::

# Teaching Experience 

* **Digital Feminism: Theory and Method for Feminism on the Internet** *Spring 2024*. Instructor of Record. Undergraduate Seminar. Sciences Po (Paris Campus). 
* **Social Networks.** *Fall 2022 and Spring 2020*. TA (Instructor: Dr. Sandra González-Bailón). Undergraduate Seminar. University of Pennsylvania 
* **Introduction to Communication Research.** *Fall 2020*. TA (Instructor: Dr. Yph Lelkes). Graduate seminar. University of Pennsylvania
* **Digital Inequality.** *Fall 2019*. TA (Instructor: Dr. Julia Ticona). Ungraduate Seminar. University of Pennsylvania. 



